#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/storage
#
# IDENTIFICATION
#    src/backend/access/storage/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/storage
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = storageam.o storageamapi.o

include $(top_srcdir)/src/backend/common.mk
